### ISSUE TITLE
The state of the Omae code could use some improvement

### ISSUE THREAD

**Issue by BenSower** [HeyOmae/Omae#11]
Heyho,

I just recently started playing SR5 and since character creation is a hassle in most systems I was happy to find your creator. Thanks for the effort! 
Still, I couldn't help but notice that your code could definitely use some refactoring and restructuring. Would it be ok, if forked you and did just that?
Just like the (apparently never finished) pull request https://github.com/HeyOmae/Omae/pull/10, I was planning to reform the code a little by 
* separating css, html and js (there's a reason they are different languages :-P)
* separating the data from the logic (you can easily extract all data objects from the code, which will improve maintainability immensely)
* finally create a proper data model
* maybe add at least some webstorage (http://www.w3schools.com/html/html5_webstorage.asp) to make saving easier

this will not take very long, but could improve your code immensely (source: I am a master computer scientist and professial javascript backend engineer :-)

Would that be ok? (I don't know if you had other plans)

**Comment by dethstrobe** [comment]
The code is total shit in all honesty. It was an experiment to try and learn JS at the time. And to say the least the state of JS has changed a lot as well as I've learned a ton since then. If you want to clean up the code, by all means please do. I can invite you to the group if you'd like as well.

I started to rebuild it using angularJS, but I wasn't too happy with the way the Yeoman generator I found structured everything. I've also been meaning to learn ReactJS, so I might just rebuild the whole thing in React to just get a project under my belt using facebook's new framework.

**Comment by BenSower** [comment]
Heyho, thanks for the quick answer!
I couldn't sleep, so I created a fast pr: https://github.com/HeyOmae/Omae/pull/12

Yeah, I've been using the exact angular-fullstack for a couple of projects now and by now I am still not a huge fan, but got used to it. I also wanted to have a look at ReactJS, so if you want to, we can create a new project using react!

Since the last release, the latest reactjs-fullstack-generator overtook the angular-fullstack on yeoman popularitywise!
https://github.com/kriasoft/react-starter-kit

Good time to get started

**Comment by dethstrobe** [comment]
I found that react-starter-kit is really bare bones compared to angular-fullstack.

With that said, lets do it. I don't have any plans for tonight. So I think starting up a new and improved Omae build on react would be awesome.

If you want to take a look at the angular version of Omae, you can at https://github.com/HeyOmae/HeyOmae.github.io/tree/src

If you take a look in the /app/assets directory you'll find some JSON files I already took from my last version of Omae.
